# Generated by Django 5.0.2 on 2024-05-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0004_railways_is_occupied_railways_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='railways',
            name='average_proivoditelnost_loko',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='railways',
            name='average_speed',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='railways',
            name='besopasnost',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='railways',
            name='debitorka',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='railways',
            name='dolya_gryzovix_otpravok',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='railways',
            name='financi_po_prochim',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='railways',
            name='kreditorka',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='railways',
            name='raspisanie_pass_poesdov',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='railways',
            name='raspisanie_prigoroda',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='railways',
            name='sebestoimost',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='railways',
            name='time_zadershka',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='railways',
            name='virychka_ot_gryzov',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=1000000),
        ),
    ]
