# Generated by Django 5.0.2 on 2024-05-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0005_railways_average_proivoditelnost_loko_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='railways',
            name='pogryzka',
            field=models.FloatField(default=1),
        ),
    ]
