# Generated by Django 5.0.2 on 2024-05-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0007_calculationresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationresult',
            name='raspisanie_prigoroda',
            field=models.FloatField(default=1),
        ),
    ]
