# Generated by Django 5.0.2 on 2024-05-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0008_calculationresult_raspisanie_prigoroda'),
    ]

    operations = [
        migrations.AddField(
            model_name='railways',
            name='current_move',
            field=models.FloatField(default=-1),
        ),
    ]
