# Generated by Django 5.0.2 on 2024-05-25 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0009_railways_current_move'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='railways',
            name='current_move',
        ),
    ]
