# Generated by Django 5.0.2 on 2024-05-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0010_remove_railways_current_move'),
    ]

    operations = [
        migrations.AddField(
            model_name='railways',
            name='current_move',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
