# Generated by Django 5.0.2 on 2024-05-27 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0012_rename_average_speed_railways_average_speed_gryz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='railways',
            name='sostoyanie_gryz',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='railways',
            name='sostoyanie_pass',
            field=models.IntegerField(default=90),
        ),
    ]
