# Generated by Django 5.0.2 on 2024-05-28 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0013_railways_sostoyanie_gryz_railways_sostoyanie_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='railways',
            name='sostoyanie_loko',
            field=models.IntegerField(default=90),
        ),
    ]
