# Generated by Django 5.0.2 on 2024-05-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0014_railways_sostoyanie_loko'),
    ]

    operations = [
        migrations.AddField(
            model_name='railways',
            name='total_score',
            field=models.FloatField(default=0),
        ),
    ]
