# Generated by Django 5.0.2 on 2024-05-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0016_railways_maks_kolvo_reisov'),
    ]

    operations = [
        migrations.AddField(
            model_name='railways',
            name='maks_kolvo_reisov_gryz',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='railways',
            name='maks_kolvo_reisov_loko',
            field=models.FloatField(default=1),
        ),
    ]
