# Generated by Django 5.0.2 on 2024-05-28 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0017_railways_maks_kolvo_reisov_gryz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('plan_value', models.FloatField()),
                ('fact_value', models.FloatField(blank=True, null=True)),
                ('railway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_site.railways')),
            ],
        ),
    ]
